 figure
 
for i=1:28
alldata=[rawExpData.data{1, 1}.EMGData.Data(:,i);...
     rawExpData.data{1, 2}.EMGData.Data(:,i);...
     rawExpData.data{1, 3}.EMGData.Data(:,i);...
     rawExpData.data{1, 4}.EMGData.Data(:,i);...
     rawExpData.data{1, 5}.EMGData.Data(:,i);...
     rawExpData.data{1, 6}.EMGData.Data(:,i);...
%      rawExpData.data{1, 13}.EMGData.Data(:,i)...
];
 subplot(3,10,i)
 plot(alldata)
 title(rawExpData.data{1, 6}.EMGData.labels(i));
end 
  
 
