 figure
 
for i=1:28
alldata=[rawExpData.data{1, 9}.EMGData.Data(:,i);...
     rawExpData.data{1, 11}.EMGData.Data(:,i);...
     rawExpData.data{1, 12}.EMGData.Data(:,i);...
     rawExpData.data{1, 13}.EMGData.Data(:,i);...
     rawExpData.data{1, 14}.EMGData.Data(:,i);...
     rawExpData.data{1, 15}.EMGData.Data(:,i);...
     rawExpData.data{1, 16}.EMGData.Data(:,i);...
     rawExpData.data{1, 17}.EMGData.Data(:,i);...
     rawExpData.data{1, 19}.EMGData.Data(:,i);...
     rawExpData.data{1, 21}.EMGData.Data(:,i);...
     rawExpData.data{1, 22}.EMGData.Data(:,i);...
     rawExpData.data{1, 24}.EMGData.Data(:,i);...
%      rawExpData.data{1, 13}.EMGData.Data(:,i)...
];
 subplot(3,10,i)
 plot(alldata)
 title(rawExpData.data{1, 9}.EMGData.labels(i));
end 
  
 
