
function Getting_EMGdata_Csv2mat_PC1(dir1, trials)
%% Import data from text file
% Script for importing data from the following text file:

% Auto-generated by MATLAB on 19-Jan-2021 16:51:28

%% Setup the Import Options
cd(dir1)

opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.Delimiter = ",";

idx=0;
for t=trials
    l=0;
    if t<10
        opts = detectImportOptions([dir1,'\Trial0',num2str(t),'.csv']);
        
    else
        opts = detectImportOptions([dir1,'\Trial',num2str(t),'.csv']);
    end
    
    opts2=opts;
    
    opts.SelectedVariableNames=opts.VariableNames(:,2:2:end);
    opts = setvaropts(opts,opts.SelectedVariableNames);
    Channels=char(opts.SelectedVariableNames);
    opts = setvaropts(opts,[1:2:length(opts.VariableNames)], "EmptyFieldRule", "auto");
    
    opts2.SelectedVariableNames=opts2.VariableNames(1,1:2:end);
    opts2 = setvaropts(opts2,opts2.SelectedVariableNames);
    opts2 = setvaropts(opts2,[2:2:length(opts2.VariableNames)], "EmptyFieldRule", "auto");
    opts2.DataLines = [3, 3];
    
    if t<10
        Data= readtable([dir1,'\Trial0',num2str(t),'.csv'], opts);
        Fs=readtable([dir1,'\Trial0',num2str(t),'.csv'], opts2);
        
    else
        Data= readtable([dir1,'\Trial',num2str(t),'.csv'], opts);
        Fs=readtable([dir1,'\Trial',num2str(t),'.csv'], opts2);
        
    end
    Fs = table2array(Fs);
    Fs=1./Fs';
    
    tend=height(Data);
    for i=2:600000:tend
        % Specify range and delimiter
        l=l+1;
        
        range=i:600000+i;
        
        if range(end)<tend
            data2=Data(i:600000+i ,:);
        else
            data2=Data(i:end,:);
        end
        
        EMGdata = table2array(data2);
        
        if t<10
            save(['EMG_Trial0',num2str(t),'_' num2str(l),'.mat'], 'EMGdata','Channels','Fs')
        else
            save(['EMG_Trial',num2str(t),'_' num2str(l),'.mat'], 'EMGdata','Channels','Fs')
        end
        
    end
end

%% Clear temporary variables
clear opts
end