function [eps] = defineEpochYoungLongAdaptation(nantype)

names={'Base', 'EarlyA', 'LateA' ,'EarlyP', 'LateP'};

eps=defineEpochs(names,...
                {'TM Base','Adaptation','Adaptation','Washout','Washout'},...
                [-40 15 -40 15 -40],...
                [0,1,0,1,0],...
                [1,0,0,1,1],...
                nantype);